base:
  api-thread-pool-size: 3
  api-retry-max-count: 2
  api-retry-duration-secs: 10

api:
  protocol: http
  host: 127.0.0.1
  port: 80
  path: /api/v1/register
  ctype: application/json

apis:
  - key: BME280_BEACON_1
    protocol: http
    host: 172.0.0.1
    port: 80
    path: /api/v1/register
    ctype: application/json

  - key: BME280_BEACON_2
    dests:
      - protocol: http
        host: 127.0.1.1
        port: 8080
        path: /api/v1/register
        ctype: application/json
      - protocol: http
        host: 127.0.1.2
        port: 9090
        path: /api/v1/register
        ctype: application/json
    
features:
  api: no

whitelist:
  - BME280_BEACON_1
  - BME280_BEACON_2