version: '3'

services:

    central:
        build:
            context: .
            dockerfile: ./DOCKER/Dockerfile
        image: ble-home-central-docker
#        restart: always
        volumes:
            - /opt/bluetooth:/var/lib/bluetooth
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
#            - /tmp/$(mktemp -d):/run
        network_mode: "host"
        tmpfs: /run
